package com.github.edgar615.jdbc.spring.dao;

import com.github.edgar615.dao.BaseDao;
import com.github.edgar615.jdbc.spring.entity.User;

/**
* This class is generated by Jdbc code generator.
*
* Table : user
*
* @author Jdbc Code Generator
*/
public interface UserDao extends BaseDao<Long, User> {

   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}
