package com.github.edgar615.jdbc.spring.entity;

import com.github.edgar615.entity.Persistent;
import com.google.common.base.MoreObjects;

/**
 * This class is generated by Jdbc code generator.
 * <p>
 * Table : user
 * remarks:
 *
 * @author Jdbc Code Generator
 */
public class User implements Persistent<Long> {

    private static final long serialVersionUID = 5705048697194337470L;

    /**
     * @Column : user_id
     * @remarks: id
     * @default:
     * @isNullable: false
     * @isAutoInc: false
     * @isPrimary: true
     * @type: -5
     * @size: 19
     */
    private Long userId;

    /**
     * @Column : username
     * @remarks: 用户名
     * @default:
     * @isNullable: true
     * @isAutoInc: false
     * @isPrimary: false
     * @type: 12
     * @size: 60
     */
    private String username;

    /**
     * @Column : nickname
     * @remarks: 昵称
     * @default:
     * @isNullable: true
     * @isAutoInc: false
     * @isPrimary: false
     * @type: 12
     * @size: 16
     */
    private String nickname;

    /**
     * @Column : mobile
     * @remarks: 手机
     * @default:
     * @isNullable: true
     * @isAutoInc: false
     * @isPrimary: false
     * @type: 12
     * @size: 11
     */
    private String mobile;

    /**
     * @Column : mail
     * @remarks: 邮箱
     * @default:
     * @isNullable: true
     * @isAutoInc: false
     * @isPrimary: false
     * @type: 12
     * @size: 60
     */
    private String mail;

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper("User")
                .add("userId", userId)
                .add("username", username)
                .add("nickname", nickname)
                .add("mobile", mobile)
                .add("mail", mail)
                .toString();
    }

    /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
    /* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}
