package com.github.edgar615.jdbc.spring.entity;

import com.github.edgar615.jdbc.JdbcSqlSupport;
import com.github.edgar615.jdbc.SqlColumn;
import com.google.common.collect.Lists;
import java.util.List;
import java.util.Map;

/**
* This class is generated by Jdbc code generator.
*
* Table : user
*
* @author Jdbc Code Generator
*/
public class UserJdbcSqlSupport implements JdbcSqlSupport<Long, User> {

    private static final long serialVersionUID = 1L;
    
    public static final String USER_ID = UserColumn.USER_ID.javaName();
    
    public static final String USERNAME = UserColumn.USERNAME.javaName();
    
    public static final String NICKNAME = UserColumn.NICKNAME.javaName();
    
    public static final String MOBILE = UserColumn.MOBILE.javaName();
    
    public static final String MAIL = UserColumn.MAIL.javaName();
    
    @Override
    public List<String> fields() {
      return Lists.newArrayList(USER_ID,
						USERNAME,
						NICKNAME,
						MOBILE,
						MAIL);
    }
    
    
    @Override
    public String primaryField() {
        return USER_ID;
    }

    @Override
    public void toMap(User user, Map<String, Object> map) {
        if (map == null) {
            return;
        }
        
        map.put(USER_ID,  user.getUserId());
        map.put(USERNAME,  user.getUsername());
        map.put(NICKNAME,  user.getNickname());
        map.put(MOBILE,  user.getMobile());
        map.put(MAIL,  user.getMail());
    }

    @Override
    public void fromMap(Map<String, Object> map, User user) {
        if (map == null) {
            return;
        }
        if (map.get(USER_ID) instanceof Long) {
            user.setUserId((Long) map.get(USER_ID));
        }
        if (map.get(USERNAME) instanceof String) {
            user.setUsername((String) map.get(USERNAME));
        }
        if (map.get(NICKNAME) instanceof String) {
            user.setNickname((String) map.get(NICKNAME));
        }
        if (map.get(MOBILE) instanceof String) {
            user.setMobile((String) map.get(MOBILE));
        }
        if (map.get(MAIL) instanceof String) {
            user.setMail((String) map.get(MAIL));
        }
        
    }

    @Override
    public void setGeneratedKey(Number key, User user) {
    
        user.setUserId(key.longValue());
    
    }

    @Override
    public Long id (User user) {
        return user.getUserId();
    }

    public static class UserColumn {
    
        public static final SqlColumn USER_ID = SqlColumn.create("user_id", "userId");
    
        public static final SqlColumn USERNAME = SqlColumn.create("username", "username");
    
        public static final SqlColumn NICKNAME = SqlColumn.create("nickname", "nickname");
    
        public static final SqlColumn MOBILE = SqlColumn.create("mobile", "mobile");
    
        public static final SqlColumn MAIL = SqlColumn.create("mail", "mail");
    
    }
   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}
