package com.github.edgar615.jdbc.spring.dao.impl;

import com.github.edgar615.dao.BaseDaoImpl;
import com.github.edgar615.jdbc.Jdbc;
import com.github.edgar615.jdbc.spring.dao.UserDao;
import com.github.edgar615.jdbc.spring.entity.User;
import com.github.edgar615.util.search.Example;
import java.util.List;
import org.springframework.stereotype.Service;

/**
* This class is generated by Jdbc code generator.
*
* Table : user
*
* @author Jdbc Code Generator
*/
@Service
public class UserDaoImpl extends BaseDaoImpl<Long, User> implements UserDao {
    
    public UserDaoImpl(Jdbc jdbc) {
        super(User.class, jdbc);
    }
    

    /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/


}
